version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pdf-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_...}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_...}
    volumes:
      - ./app:/app/app
      - pdf_temp:/tmp/pdf-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Celery worker for background tasks
  # celery:
  #   build: .
  #   command: celery -A app.celery worker --loglevel=info
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   volumes:
  #     - ./app:/app/app

  # Optional: Celery beat for scheduled tasks
  # celery-beat:
  #   build: .
  #   command: celery -A app.celery beat --loglevel=info
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  redis_data:
  pdf_temp:
